In [2]:
!pip install tensorflow

Requirement already satisfied: tensorflow in c:\users\cw\anaconda3\lib\site-packages (2.20.0)
Requirement already satisfied: absl-py>=1.0.0 in c:\users\cw\anaconda3\lib\site-packages (from tensorflow) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in c:\users\cw\anaconda3\lib\site-packages (from tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=24.3.25 in c:\users\cw\anaconda3\lib\site-packages (from tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in c:\users\cw\anaconda3\lib\site-packages (from tensorflow) (0.7.0)
Requirement already satisfied: google_pasta>=0.1.1 in c:\users\cw\anaconda3\lib\site-packages (from tensorflow) (0.2.0)
Requirement already satisfied: libclang>=13.0.0 in c:\users\cw\anaconda3\lib\site-packages (from tensorflow) (18.1.1)
Requirement already satisfied: opt_einsum>=2.3.2 in c:\users\cw\anaconda3\lib\site-packages (from tensorflow) (3.4.0)
Requirement already satisfied: packaging in c:\users\cw\anaconda3\lib\site-packages (from tensorflow) (24.2)
Requirement already satisfied: protobuf>=5.28.0 in c:\users\cw\appdata\roaming\python\python313\site-packages (from tensorflow) (6.33.2)
Requirement already satisfied: requests<3,>=2.21.0 in c:\users\cw\anaconda3\lib\site-packages (from tensorflow) (2.32.3)
Requirement already satisfied: setuptools in c:\users\cw\anaconda3\lib\site-packages (from tensorflow) (72.1.0)
Requirement already satisfied: six>=1.12.0 in c:\users\cw\appdata\roaming\python\python313\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in c:\users\cw\anaconda3\lib\site-packages (from tensorflow) (3.3.0)
Requirement already satisfied: typing_extensions>=3.6.6 in c:\users\cw\appdata\roaming\python\python313\site-packages (from tensorflow) (4.15.0)
Requirement already satisfied: wrapt>=1.11.0 in c:\users\cw\anaconda3\lib\site-packages (from tensorflow) (1.17.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in c:\users\cw\anaconda3\lib\site-packages (from tensorflow) (1.78.0)
Requirement already satisfied: tensorboard~=2.20.0 in c:\users\cw\anaconda3\lib\site-packages (from tensorflow) (2.20.0)
Requirement already satisfied: keras>=3.10.0 in c:\users\cw\anaconda3\lib\site-packages (from tensorflow) (3.13.2)
Requirement already satisfied: numpy>=1.26.0 in c:\users\cw\anaconda3\lib\site-packages (from tensorflow) (2.1.3)
Requirement already satisfied: h5py>=3.11.0 in c:\users\cw\anaconda3\lib\site-packages (from tensorflow) (3.12.1)
Requirement already satisfied: ml_dtypes<1.0.0,>=0.5.1 in c:\users\cw\anaconda3\lib\site-packages (from tensorflow) (0.5.4)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\cw\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\cw\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\cw\appdata\roaming\python\python313\site-packages (from requests<3,>=2.21.0->tensorflow) (2.6.2)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\cw\anaconda3\lib\site-packages (from requests<3,>=2.21.0->tensorflow) (2026.1.4)
Requirement already satisfied: markdown>=2.6.8 in c:\users\cw\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (3.8)
Requirement already satisfied: pillow in c:\users\cw\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (11.1.0)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in c:\users\cw\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in c:\users\cw\anaconda3\lib\site-packages (from tensorboard~=2.20.0->tensorflow) (3.1.3)
Requirement already satisfied: wheel<1.0,>=0.23.0 in c:\users\cw\anaconda3\lib\site-packages (from astunparse>=1.6.0->tensorflow) (0.45.1)
Requirement already satisfied: rich in c:\users\cw\anaconda3\lib\site-packages (from keras>=3.10.0->tensorflow) (13.9.4)
Requirement already satisfied: namex in c:\users\cw\anaconda3\lib\site-packages (from keras>=3.10.0->tensorflow) (0.1.0)
Requirement already satisfied: optree in c:\users\cw\anaconda3\lib\site-packages (from keras>=3.10.0->tensorflow) (0.19.0)
Requirement already satisfied: MarkupSafe>=2.1.1 in c:\users\cw\anaconda3\lib\site-packages (from werkzeug>=1.0.1->tensorboard~=2.20.0->tensorflow) (3.0.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\cw\anaconda3\lib\site-packages (from rich->keras>=3.10.0->tensorflow) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\cw\anaconda3\lib\site-packages (from rich->keras>=3.10.0->tensorflow) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\cw\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.10.0->tensorflow) (0.1.0)

In [13]:
!pip install keras

Requirement already satisfied: keras in c:\users\cw\anaconda3\lib\site-packages (3.13.2)
Requirement already satisfied: absl-py in c:\users\cw\anaconda3\lib\site-packages (from keras) (2.4.0)
Requirement already satisfied: numpy in c:\users\cw\anaconda3\lib\site-packages (from keras) (2.1.3)
Requirement already satisfied: rich in c:\users\cw\anaconda3\lib\site-packages (from keras) (13.9.4)
Requirement already satisfied: namex in c:\users\cw\anaconda3\lib\site-packages (from keras) (0.1.0)
Requirement already satisfied: h5py in c:\users\cw\anaconda3\lib\site-packages (from keras) (3.12.1)
Requirement already satisfied: optree in c:\users\cw\anaconda3\lib\site-packages (from keras) (0.19.0)
Requirement already satisfied: ml-dtypes in c:\users\cw\anaconda3\lib\site-packages (from keras) (0.5.4)
Requirement already satisfied: packaging in c:\users\cw\anaconda3\lib\site-packages (from keras) (24.2)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\cw\appdata\roaming\python\python313\site-packages (from optree->keras) (4.15.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\cw\anaconda3\lib\site-packages (from rich->keras) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\cw\anaconda3\lib\site-packages (from rich->keras) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\cw\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras) (0.1.0)

In [24]:
!pip install scikeras

Collecting scikeras
  Downloading scikeras-0.13.0-py3-none-any.whl.metadata (3.1 kB)
Requirement already satisfied: keras>=3.2.0 in c:\users\cw\anaconda3\lib\site-packages (from scikeras) (3.13.2)
Requirement already satisfied: scikit-learn>=1.4.2 in c:\users\cw\anaconda3\lib\site-packages (from scikeras) (1.6.1)
Requirement already satisfied: absl-py in c:\users\cw\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (2.4.0)
Requirement already satisfied: numpy in c:\users\cw\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (2.1.3)
Requirement already satisfied: rich in c:\users\cw\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (13.9.4)
Requirement already satisfied: namex in c:\users\cw\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (0.1.0)
Requirement already satisfied: h5py in c:\users\cw\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (3.12.1)
Requirement already satisfied: optree in c:\users\cw\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (0.19.0)
Requirement already satisfied: ml-dtypes in c:\users\cw\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (0.5.4)
Requirement already satisfied: packaging in c:\users\cw\anaconda3\lib\site-packages (from keras>=3.2.0->scikeras) (24.2)
Requirement already satisfied: scipy>=1.6.0 in c:\users\cw\anaconda3\lib\site-packages (from scikit-learn>=1.4.2->scikeras) (1.15.3)
Requirement already satisfied: joblib>=1.2.0 in c:\users\cw\anaconda3\lib\site-packages (from scikit-learn>=1.4.2->scikeras) (1.4.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\cw\appdata\roaming\python\python313\site-packages (from scikit-learn>=1.4.2->scikeras) (3.6.0)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\cw\appdata\roaming\python\python313\site-packages (from optree->keras>=3.2.0->scikeras) (4.15.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\cw\anaconda3\lib\site-packages (from rich->keras>=3.2.0->scikeras) (2.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\cw\anaconda3\lib\site-packages (from rich->keras>=3.2.0->scikeras) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\cw\anaconda3\lib\site-packages (from markdown-it-py>=2.2.0->rich->keras>=3.2.0->scikeras) (0.1.0)
Downloading scikeras-0.13.0-py3-none-any.whl (26 kB)
Installing collected packages: scikeras
Successfully installed scikeras-0.13.0

In [38]:

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from scikeras.wrappers import KerasClassifier
import warnings 
warnings.filterwarnings('ignore')

## Load Dataset

In [31]:
df = pd.read_csv('sonardataset.csv')
df.head()

,x_1,x_2,x_3,x_4,x_5,x_6,x_7,x_8,x_9,x_10,...,x_52,x_53,x_54,x_55,x_56,x_57,x_58,x_59,x_60,Y
0,0.0200,0.0371,0.0428,0.0207,0.0954,0.0986,0.1539,0.1601,0.3109,0.2111,...,0.0027,0.0065,0.0159,0.0072,0.0167,0.0180,0.0084,0.0090,0.0032,R
1,0.0453,0.0523,0.0843,0.0689,0.1183,0.2583,0.2156,0.3481,0.3337,0.2872,...,0.0084,0.0089,0.0048,0.0094,0.0191,0.0140,0.0049,0.0052,0.0044,R
2,0.0262,0.0582,0.1099,0.1083,0.0974,0.2280,0.2431,0.3771,0.5598,0.6194,...,0.0232,0.0166,0.0095,0.0180,0.0244,0.0316,0.0164,0.0095,0.0078,R
3,0.0100,0.0171,0.0623,0.0205,0.0205,0.0368,0.1098,0.1276,0.0598,0.1264,...,0.0121,0.0036,0.0150,0.0085,0.0073,0.0050,0.0044,0.0040,0.0117,R
4,0.0762,0.0666,0.0481,0.0394,0.0590,0.0649,0.1209,0.2467,0.3564,0.4459,...,0.0031,0.0054,0.0105,0.0110,0.0015,0.0072,0.0048,0.0107,0.0094,R

## Data Exploration

In [32]:

print("Dataset Shape:", df.shape)
df.info()

Dataset Shape: (208, 61)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 61 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   x_1     208 non-null    float64
 1   x_2     208 non-null    float64
 2   x_3     208 non-null    float64
 3   x_4     208 non-null    float64
 4   x_5     208 non-null    float64
 5   x_6     208 non-null    float64
 6   x_7     208 non-null    float64
 7   x_8     208 non-null    float64
 8   x_9     208 non-null    float64
 9   x_10    208 non-null    float64
 10  x_11    208 non-null    float64
 11  x_12    208 non-null    float64
 12  x_13    208 non-null    float64
 13  x_14    208 non-null    float64
 14  x_15    208 non-null    float64
 15  x_16    208 non-null    float64
 16  x_17    208 non-null    float64
 17  x_18    208 non-null    float64
 18  x_19    208 non-null    float64
 19  x_20    208 non-null    float64
 20  x_21    208 non-null    float64
 21  x_22    208 non-null    float64
 22  x_23    208 non-null    float64
 23  x_24    208 non-null    float64
 24  x_25    208 non-null    float64
 25  x_26    208 non-null    float64
 26  x_27    208 non-null    float64
 27  x_28    208 non-null    float64
 28  x_29    208 non-null    float64
 29  x_30    208 non-null    float64
 30  x_31    208 non-null    float64
 31  x_32    208 non-null    float64
 32  x_33    208 non-null    float64
 33  x_34    208 non-null    float64
 34  x_35    208 non-null    float64
 35  x_36    208 non-null    float64
 36  x_37    208 non-null    float64
 37  x_38    208 non-null    float64
 38  x_39    208 non-null    float64
 39  x_40    208 non-null    float64
 40  x_41    208 non-null    float64
 41  x_42    208 non-null    float64
 42  x_43    208 non-null    float64
 43  x_44    208 non-null    float64
 44  x_45    208 non-null    float64
 45  x_46    208 non-null    float64
 46  x_47    208 non-null    float64
 47  x_48    208 non-null    float64
 48  x_49    208 non-null    float64
 49  x_50    208 non-null    float64
 50  x_51    208 non-null    float64
 51  x_52    208 non-null    float64
 52  x_53    208 non-null    float64
 53  x_54    208 non-null    float64
 54  x_55    208 non-null    float64
 55  x_56    208 non-null    float64
 56  x_57    208 non-null    float64
 57  x_58    208 non-null    float64
 58  x_59    208 non-null    float64
 59  x_60    208 non-null    float64
 60  Y       208 non-null    object
dtypes: float64(60), object(1)
memory usage: 99.3+ KB

In [33]:

df.describe()

,x_1,x_2,x_3,x_4,x_5,x_6,x_7,x_8,x_9,x_10,...,x_51,x_52,x_53,x_54,x_55,x_56,x_57,x_58,x_59,x_60
count,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,...,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000,208.000000
mean,0.029164,0.038437,0.043832,0.053892,0.075202,0.104570,0.121747,0.134799,0.178003,0.208259,...,0.016069,0.013420,0.010709,0.010941,0.009290,0.008222,0.007820,0.007949,0.007941,0.006507
std,0.022991,0.032960,0.038428,0.046528,0.055552,0.059105,0.061788,0.085152,0.118387,0.134416,...,0.012008,0.009634,0.007060,0.007301,0.007088,0.005736,0.005785,0.006470,0.006181,0.005031
min,0.001500,0.000600,0.001500,0.005800,0.006700,0.010200,0.003300,0.005500,0.007500,0.011300,...,0.000000,0.000800,0.000500,0.001000,0.000600,0.000400,0.000300,0.000300,0.000100,0.000600
25%,0.013350,0.016450,0.018950,0.024375,0.038050,0.067025,0.080900,0.080425,0.097025,0.111275,...,0.008425,0.007275,0.005075,0.005375,0.004150,0.004400,0.003700,0.003600,0.003675,0.003100
50%,0.022800,0.030800,0.034300,0.044050,0.062500,0.092150,0.106950,0.112100,0.152250,0.182400,...,0.013900,0.011400,0.009550,0.009300,0.007500,0.006850,0.005950,0.005800,0.006400,0.005300
75%,0.035550,0.047950,0.057950,0.064500,0.100275,0.134125,0.154000,0.169600,0.233425,0.268700,...,0.020825,0.016725,0.014900,0.014500,0.012100,0.010575,0.010425,0.010350,0.010325,0.008525
max,0.137100,0.233900,0.305900,0.426400,0.401000,0.382300,0.372900,0.459000,0.682800,0.710600,...,0.100400,0.070900,0.039000,0.035200,0.044700,0.039400,0.035500,0.044000,0.036400,0.043900

##  Data Preprocessing

In [34]:

X = df.iloc[:, :-1]
y = df.iloc[:, -1]

# Encode target variable
encoder = LabelEncoder()
y = encoder.fit_transform(y)

# Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# Feature scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## Build Basic ANN Model

In [39]:

model = Sequential()

model.add(Dense(32, input_dim=X_train.shape[1], activation='relu'))
model.add(Dense(16, activation='relu'))
model.add(Dense(1, activation='sigmoid'))

model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

history = model.fit(
    X_train, y_train,
    epochs=50,
    batch_size=10,
    validation_split=0.2,
    verbose=1
)

Epoch 1/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 3s 55ms/step - accuracy: 0.6061 - loss: 0.6700 - val_accuracy: 0.6765 - val_loss: 0.5855
Epoch 2/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.6970 - loss: 0.5579 - val_accuracy: 0.7059 - val_loss: 0.5472
Epoch 3/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.7500 - loss: 0.4855 - val_accuracy: 0.7353 - val_loss: 0.5109
Epoch 4/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.8258 - loss: 0.4266 - val_accuracy: 0.7647 - val_loss: 0.4822
Epoch 5/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.8485 - loss: 0.3783 - val_accuracy: 0.7353 - val_loss: 0.4748
Epoch 6/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.8788 - loss: 0.3394 - val_accuracy: 0.7941 - val_loss: 0.4600
Epoch 7/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9015 - loss: 0.3066 - val_accuracy: 0.7941 - val_loss: 0.4454
Epoch 8/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9167 - loss: 0.2761 - val_accuracy: 0.7941 - val_loss: 0.4338
Epoch 9/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9242 - loss: 0.2505 - val_accuracy: 0.7941 - val_loss: 0.4268
Epoch 10/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9394 - loss: 0.2288 - val_accuracy: 0.8235 - val_loss: 0.4223
Epoch 11/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9470 - loss: 0.2068 - val_accuracy: 0.7647 - val_loss: 0.4209
Epoch 12/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9470 - loss: 0.1916 - val_accuracy: 0.7647 - val_loss: 0.4157
Epoch 13/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 0.9470 - loss: 0.1723 - val_accuracy: 0.7941 - val_loss: 0.4138
Epoch 14/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9773 - loss: 0.1566 - val_accuracy: 0.7941 - val_loss: 0.4027
Epoch 15/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 0.9773 - loss: 0.1420 - val_accuracy: 0.7941 - val_loss: 0.3939
Epoch 16/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9773 - loss: 0.1296 - val_accuracy: 0.7941 - val_loss: 0.4029
Epoch 17/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step - accuracy: 0.9773 - loss: 0.1180 - val_accuracy: 0.7941 - val_loss: 0.4094
Epoch 18/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 0.9848 - loss: 0.1069 - val_accuracy: 0.7941 - val_loss: 0.4102
Epoch 19/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 0.9924 - loss: 0.0984 - val_accuracy: 0.7941 - val_loss: 0.4139
Epoch 20/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 0.9924 - loss: 0.0899 - val_accuracy: 0.7941 - val_loss: 0.4092
Epoch 21/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0820 - val_accuracy: 0.7941 - val_loss: 0.4163
Epoch 22/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0745 - val_accuracy: 0.7941 - val_loss: 0.4143
Epoch 23/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step - accuracy: 1.0000 - loss: 0.0681 - val_accuracy: 0.7941 - val_loss: 0.4145
Epoch 24/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0618 - val_accuracy: 0.7941 - val_loss: 0.4226
Epoch 25/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0569 - val_accuracy: 0.7941 - val_loss: 0.4287
Epoch 26/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0522 - val_accuracy: 0.7941 - val_loss: 0.4369
Epoch 27/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step - accuracy: 1.0000 - loss: 0.0471 - val_accuracy: 0.7647 - val_loss: 0.4528
Epoch 28/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0433 - val_accuracy: 0.7647 - val_loss: 0.4592
Epoch 29/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0393 - val_accuracy: 0.7647 - val_loss: 0.4606
Epoch 30/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0362 - val_accuracy: 0.7647 - val_loss: 0.4714
Epoch 31/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0331 - val_accuracy: 0.7647 - val_loss: 0.4811
Epoch 32/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0303 - val_accuracy: 0.7647 - val_loss: 0.4865
Epoch 33/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0278 - val_accuracy: 0.7647 - val_loss: 0.4962
Epoch 34/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0258 - val_accuracy: 0.7647 - val_loss: 0.4894
Epoch 35/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0238 - val_accuracy: 0.7647 - val_loss: 0.4774
Epoch 36/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step - accuracy: 1.0000 - loss: 0.0218 - val_accuracy: 0.7647 - val_loss: 0.4921
Epoch 37/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0201 - val_accuracy: 0.7647 - val_loss: 0.5076
Epoch 38/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0184 - val_accuracy: 0.7647 - val_loss: 0.5131
Epoch 39/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0172 - val_accuracy: 0.7647 - val_loss: 0.5257
Epoch 40/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0162 - val_accuracy: 0.7647 - val_loss: 0.5412
Epoch 41/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0151 - val_accuracy: 0.7647 - val_loss: 0.5460
Epoch 42/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0139 - val_accuracy: 0.7647 - val_loss: 0.5477
Epoch 43/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0131 - val_accuracy: 0.7647 - val_loss: 0.5484
Epoch 44/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0123 - val_accuracy: 0.7647 - val_loss: 0.5485
Epoch 45/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0116 - val_accuracy: 0.7647 - val_loss: 0.5539
Epoch 46/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0109 - val_accuracy: 0.7647 - val_loss: 0.5590
Epoch 47/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step - accuracy: 1.0000 - loss: 0.0103 - val_accuracy: 0.7647 - val_loss: 0.5662
Epoch 48/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0097 - val_accuracy: 0.7647 - val_loss: 0.5744
Epoch 49/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step - accuracy: 1.0000 - loss: 0.0092 - val_accuracy: 0.7353 - val_loss: 0.5816
Epoch 50/50
14/14 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step - accuracy: 1.0000 - loss: 0.0087 - val_accuracy: 0.7353 - val_loss: 0.5825

##  Model Evaluation

In [36]:

y_pred = (model.predict(X_test) > 0.5).astype(int)

print("Accuracy:", accuracy_score(y_test, y_pred))

print("\nClassification Report")
print(classification_report(y_test, y_pred))

print("\nConfusion Matrix")
print(confusion_matrix(y_test, y_pred))

WARNING:tensorflow:5 out of the last 5 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x000001F7BDB8F6A0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
WARNING:tensorflow:6 out of the last 6 calls to <function TensorFlowTrainer.make_predict_function.<locals>.one_step_on_data_distributed at 0x000001F7BDB8F6A0> triggered tf.function retracing. Tracing is expensive and the excessive number of tracings could be due to (1) creating @tf.function repeatedly in a loop, (2) passing tensors with different shapes, (3) passing Python objects instead of tensors. For (1), please define your @tf.function outside of the loop. For (2), @tf.function has reduce_retracing=True option that can avoid unnecessary retracing. For (3), please refer to https://www.tensorflow.org/guide/function#controlling_retracing and https://www.tensorflow.org/api_docs/python/tf/function for  more details.
2/2 ━━━━━━━━━━━━━━━━━━━━ 0s 163ms/step
Accuracy: 0.8571428571428571

Classification Report
              precision    recall  f1-score   support

           0       0.95      0.81      0.88        26
           1       0.75      0.94      0.83        16

    accuracy                           0.86        42
   macro avg       0.85      0.87      0.85        42
weighted avg       0.88      0.86      0.86        42


Confusion Matrix
[[21  5]
 [ 1 15]]

##  Hyperparameter Tuning (Grid Search)

In [37]:
neurons_list = [16, 32]
activation_list = ['relu', 'tanh']

best_accuracy = 0
best_params = {}

for neurons in neurons_list:
    for activation in activation_list:
        
        model = Sequential()
        model.add(Dense(neurons, input_dim=X_train.shape[1], activation=activation))
        model.add(Dense(neurons//2, activation=activation))
        model.add(Dense(1, activation='sigmoid'))
        
        model.compile(
            optimizer='adam',
            loss='binary_crossentropy',
            metrics=['accuracy']
        )
        
        model.fit(X_train, y_train, epochs=50, batch_size=10, verbose=0)
        
        loss, acc = model.evaluate(X_test, y_test, verbose=0)
        
        print("Neurons:", neurons, "Activation:", activation, "Accuracy:", acc)
        
        if acc > best_accuracy:
            best_accuracy = acc
            best_params = {"neurons": neurons, "activation": activation}

print("\nBest Accuracy:", best_accuracy)
print("Best Parameters:", best_params)

C:\Users\cw\anaconda3\Lib\site-packages\keras\src\layers\core\dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Neurons: 16 Activation: relu Accuracy: 0.8809523582458496
Neurons: 16 Activation: tanh Accuracy: 0.8809523582458496
Neurons: 32 Activation: relu Accuracy: 0.9047619104385376
Neurons: 32 Activation: tanh Accuracy: 0.9523809552192688

Best Accuracy: 0.9523809552192688
Best Parameters: {'neurons': 32, 'activation': 'tanh'}

## Discussion


### Observations

- The **default ANN model** achieved a baseline accuracy on the test dataset.
- Using **GridSearchCV**, multiple hyperparameters such as:
  - number of neurons
  - activation function
  - batch size
  - number of epochs
  were tuned.
- The tuned model generally improves performance because it finds better combinations of network architecture and training parameters.

### Conclusion

Hyperparameter tuning significantly impacts ANN performance. Selecting optimal parameters improves model accuracy and generalization ability.